version: '3.9'

services:
  fuel-tracker-database:
    build: "./database"
    container_name: ft-db
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_DB: fuel_tracker
      PGDATA: /data
    restart: "always"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "../.fuel-tracker-db:/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  fuel-tracker-backend:
    build: "."
    container_name: ft-backend
    environment:
      DATABASE_URL: "postgres://${PG_USERNAME}:${PG_PASSWORD}@fuel-tracker-database:5432/fuel_tracker"
    restart: "always"
    depends_on:
      fuel-tracker-database:
        condition: service_healthy
    ports:
      - "127.0.0.1:9006:9006"

  pgadmin:
    image: dpage/pgadmin4
    restart: "always"
    ports:
      - "127.0.0.1:9002:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}