version: '3.9'

services:
  fuel-tracker-database:
    build: "./database"
    container_name: ft-db
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: fuel_tracker
      PGDATA: /data
    expose:
      - "5432"
    volumes:
      - "../.fuel-tracker-db:/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  fuel-tracker-backend:
    build: "."
    container_name: ft-backend
    environment:
      DATABASE_URL: "postgres://postgres:${PG_PASSWORD}@fuel-tracker-database:5432/fuel_tracker"
    restart: "on-failure:5"
    depends_on:
      fuel-tracker-database:
        condition: service_healthy
    ports:
      - "127.0.0.1:9006:9006"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 127.0.0.1:9002:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=mywebserviceasdf@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=adminadminluna