apiVersion: v1
kind: Service
metadata:
  name: ft-database-service
spec:
  type: NodePort
  selector:
    app: ft-database-service
  ports:
    - name: "postgres"
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432