name: Build and Test
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        working-directory: ./src

      - name: Set up Go
        working-directory: ./src
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        working-directory: ./src
        run: go build -v

      - name: Test
        working-directory: ./src
        run: go test -v -coverprofile=coverage.out